### PR TITLE
chore: bump dependencies and rust-toolchain

### PR DESCRIPTION
**Pull request by zeroqn**
- bump rust-toolchain to 1.63.0, required by ckb-vm-definitions v0.21.4
- bump ckb dependencies to 0.104.0
- bump ckb-vm to 0.21.3
- bump other dependencies by `cargo audit fix`
- bump blake2b-ref to 0.3.1
- enable ckb-rocksdb march-native feature

### CODE REVIEW

**Comment by blckngm** [comment]
👍

There was a `TransactionWithStatus` shim (in `gw-jsonrpc-types`). Could it be removed now?

**Comment by zeroqn** [comment]
> +1
> 
> There was a `TransactionWithStatus` shim (in `gw-jsonrpc-types`). Could it be removed now?

Removed in commit https://github.com/nervosnetwork/godwoken/pull/779/commits/84dc5bf5c7679a29091248839bad930d554ee80f

**Review by blckngm — DISMISSED** [review]

**Review by magicalne — DISMISSED** [review]

**Comment by jjyr** [comment]
Please use https://crates.io/crates/blake2b-ref/0.3.1

**Comment by zeroqn** [comment]
> Please use https://crates.io/crates/blake2b-ref/0.3.1

bump in https://github.com/nervosnetwork/godwoken/pull/779/commits/84140e1889804ddda77a4201f60e6d7ca82d9c3e

**Comment by zeroqn** [comment]
I think we can wait rust 1.63 (will be released tonight).

**Review by jjyr — DISMISSED** [review]

**Comment by blckngm** [comment]
If we update rocksdb, we should use the `march-native` feature.

**Comment by zeroqn** [comment]
> If we update rocksdb, we should use the `march-native` feature.

This pr ?
  - https://github.com/nervosnetwork/godwoken-docker-prebuilds/pull/67

**Comment by blckngm** [comment]
ckb-rocksdb 0.18.3 with `march-native` targets the native CPU, like 0.18.1:

https://github.com/nervosnetwork/rust-rocksdb/pull/41

We only use `PORTABLE=1 SSE=1` when building docker image.

**Review by Flouse — DISMISSED** [review]

**Comment by zeroqn** [comment]
> ckb-rocksdb 0.18.3 with `march-native` targets the native CPU, like 0.18.1:
> 
> [nervosnetwork/rust-rocksdb#41](https://github.com/nervosnetwork/rust-rocksdb/pull/41)
> 
> We only use `PORTABLE=1 SSE=1` when building docker image.

enable march-native feature in https://github.com/nervosnetwork/godwoken/pull/779/commits/94e79b116c5736a5e6b6bb18d7863dda5696b056

**Review by jjyr — APPROVED** [review]

**Review by blckngm — APPROVED** [review]

**Pull request merged**
