### PR TITLE
test: make scripts_tests pass

### PR DESCRIPTION
**Pull request by keroro520**
Includes scripts_tests in CI pipeline.

### CODE REVIEW

**Comment by blckngm** [comment]
Scripts CI action is not triggered? What can we do about this?

**Comment by keroro520** [comment]
> Scripts CI action is not triggered? What can we do about this?

It's a good question! At the [latest commit](b00346b), I added a path trigger to .github/workflows/scripts.yml, and the scripts test was triggered. Let's wait for the running result.

**Comment by blckngm** [comment]
To prevent godwoken changes making scripts tests fail in the future, I suggest we run or at least check (`cargo check`) scripts tests when relevant godwoken code changes.

**Comment by keroro520** [comment]
> To prevent godwoken changes making scripts tests fail in the future, I suggest we run or at least check (`cargo check`) scripts tests when relevant godwoken code changes.

How about modifying https://github.com/godwokenrises/godwoken/blob/develop/.github/workflows/rust.yml#L26
```yaml
      - name: Cargo clippy check
        env:
          RUSTFLAGS: -D warnings
        run: cargo clippy --all-targets
```

to

```yaml
      - name: Cargo clippy check
        env:
          RUSTFLAGS: -D warnings
        run: cargo clippy --tests --all-features --all-targets
```

**Comment by blckngm** [comment]
> ```yaml
>       - name: Cargo clippy check
>         env:
>           RUSTFLAGS: -D warnings
>         run: cargo clippy --tests --all-features --all-targets
> ```

Good idea.

**Review by blckngm — APPROVED** [review]

**Review by jjyr — APPROVED** [review]

**Pull request merged**
