### PR TITLE
chore(web3): Bump node version to v18

### PR DESCRIPTION
**Pull request by classicalliu**

### CODE REVIEW

**Review by Flouse — DISMISSED** [review]

**Review by Simon-Tl — DISMISSED** [review]

**Comment by RetricSu** [comment]
please wait for me to release a new manual_build image for kicker before merging this pr

**Comment by RetricSu** [comment]
> please wait for me to release a new manual_build image for kicker before merging this pr

here is the new image:

- https://hub.docker.com/layers/retricsu/godwoken-manual-build/node18/images/sha256-27390ad30f1ccbd4e23700eb9db3a602f4f16bbb14220b01abd30b9b159e3567?context=repo

**Comment by Flouse** [comment]
> here is the new image:
> 
> * https://hub.docker.com/layers/retricsu/godwoken-manual-build/node18/images/sha256-27390ad30f1ccbd4e23700eb9db3a602f4f16bbb14220b01abd30b9b159e3567?context=repo

cc @classicalliu

**Comment by classicalliu** [comment]
- https://github.com/godwokenrises/godwoken/pull/998

Remove node engine limit for Kicker init failed. Re-add later

**Pull request closed without merging**
