### PR TITLE
chore(ci): integration test through chat bot

### PR DESCRIPTION
**Pull request by zeroqn**

### CODE REVIEW

**Comment by zeroqn** [comment]
### Running integration test

Workflow Run Id: [2239897183](https://github.com/nervosnetwork/godwoken-tests/actions/runs/2239897183)
  
### Components:

- prebuilds: [v0.10.x-rc,v0.10.x-rc-202204250407](https://github.com/orgs/nervosnetwork/packages/container/godwoken-prebuilds/20513103)
- godwoken: [c6bffca](https://github.com/nervosnetwork/godwoken/commit/c6bffcae9469cb6b79079d8de20cc28a552623bd)
- scripts: [prebuilds eecda7a](https://github.com/nervosnetwork/godwoken-scripts/commit/eecda7a0e747ca2a4d27b133d6a551cef415aaa7)
- polyjuice: [prebuilds 15b53ce](https://github.com/nervosnetwork/godwoken-polyjuice/commit/15b53ce339d9418dedc38bb389c093d2c73e841d)
- kicker: [c980624](https://github.com/RetricSu/godwoken-kicker/commit/c980624ed3e63a2602178eba7a9ce2d570853f4c)
- tests: [caf3f54](https://github.com/nervosnetwork/godwoken-tests/commit/caf3f540270da1bdf056c7df40fb4500b863083e)
### Manually running integration test

Post a comment contains
```
/itest
[prebuilds: tag]
[godwoken: branch/ref]
[scripts: branch/ref]
[polyjuice: branch/ref]
[web3: branch/ref]
[kicker: branch/ref]
[tests: branch/ref]
```

Note: ```[]``` means optional, for example

```
/itest
prebuilds: dev-202203280240
godwoken: develop
scripts: 81676d9d53ffdf5bbaa60483928d07da16eb4a88
polyjuice: e37553b9
```
### Run Result
**failure**

**Comment by jjyr** [comment]
Please rebase.

How do we trigger a integration test after this PR?

**Comment by zeroqn** [comment]
> Please rebase.
> 
> How do we trigger a integration test after this PR?

Create pr as usual, or post `/itest` comment to trigger it manually.

**Review by jjyr — APPROVED** [review]

**Review by keroro520 — APPROVED** [review]

**Review by Flouse — APPROVED** [review]

**Pull request merged**
