### PR TITLE
chore: update ckb deps for the upcoming ckb 2023 hardfork

### PR DESCRIPTION
**Pull request by blckngm**
#### Ckb 2023 blocks may contain data2 transactions. We need to update godwken ckb deps.

* Generator still uses vm version 1. Aot is no longer supported as of ckb-vm 0.24, so it's removed.
* Script tests use ckb 2023 consensus

### CODE REVIEW

**Review by jjyr — DISMISSED** [review]

**Comment by jjyr** [comment]
@blckngm @Flouse  this PR is marked as draft PR, can we merge it?

**Comment by blckngm** [comment]
We should update ckb deps to 0.111.0. Will update later.

**Review by jjyr — APPROVED** [review]

**Comment by Flouse** [comment]
### No space left on device in CI https://github.com/godwokenrises/godwoken/actions/runs/6558239416/job/17811410009?pr=1081#step:17:852

I will handle this issue.

**Comment by Flouse** [comment]
- replaced by https://github.com/godwokenrises/godwoken/pull/1106

**Pull request closed without merging**
